import type { Locale } from "@/lib/i18n";

const copy = {
  es: {
    title: "Profundidad Beta Live",
    description:
      "Capas internas que amplían el observatory con datos reales ya existentes de Futures Lab.",
    sections: {
      scanner: {
        title: "Scanner Detail",
        description: "Detalle del escaneo y contexto de ranking por mercado.",
      },
      decisions: {
        title: "Decision Context",
        description: "Contexto ampliado de decisiones recientes del laboratorio.",
      },
      setups: {
        title: "Setup Depth",
        description: "Memoria histórica de setups con métricas de desempeño más profundas.",
      },
      ghosts: {
        title: "Ghost Outcomes",
        description: "Lectura post-evaluación de oportunidades rechazadas.",
      },
      diagnostics: {
        title: "Diagnostic Context",
        description: "Contexto operativo sobre supervivencia de candidates y razones de rechazo.",
      },
    },
    empty: "No hay datos beta live disponibles.",
    fields: {
      scanBatchId: "Batch",
      lastPrice: "Último precio",
      quoteVolume: "Volumen cotizado",
      rangePct: "Rango",
      longShortBalance: "Balance long/short",
      orderValid: "Orden válida",
      rankingReason: "Razón de ranking",
      priceChangePct: "Cambio %",
      trendStrengthPct: "Fuerza de tendencia",
      realizedVolatilityPct: "Volatilidad realizada",
      fundingRate: "Funding",
      decisionType: "Tipo",
      environment: "Entorno",
      directionHint: "Sesgo",
      selectedSide: "Lado",
      signalOk: "Signal OK",
      estimatedRrRatio: "R/R estimado",
      trendAlignmentLabel: "Alineación",
      trendSupportsDirection: "La tendencia apoya",
      setupKey: "Setup",
      setupKeyVersion: "Versión",
      oracleRecommendation: "Oracle",
      capitalProfile: "Perfil de capital",
      operatingCapital: "Capital operativo",
      autoEntryEnabled: "Auto entry",
      autoExitEnabled: "Auto exit",
      takeProfitPct: "TP %",
      stopLossPct: "SL %",
      takeProfitUsdt: "TP USDT",
      stopLossUsdt: "SL USDT",
      leverage: "Apalancamiento",
      tradeCount: "Operaciones",
      winCount: "Victorias",
      winRate: "Win rate",
      pnlTotal: "PnL total",
      averagePnl: "PnL promedio",
      averagePnlPct: "PnL % promedio",
      averageCapitalReference: "Capital ref.",
      averageHoldTicks: "Hold ticks",
      averageWinPnl: "Win PnL",
      averageLossAbs: "Loss abs.",
      lastRealizedPnl: "Último PnL",
      lastRealizedPnlPct: "Último PnL %",
      cooldownMultiplier: "Cooldown",
      suggestedTakeProfitUsdt: "TP sugerido",
      suggestedStopLossUsdt: "SL sugerido",
      lastCloseReason: "Último cierre",
      healthScore: "Salud",
      summaryText: "Resumen",
      lastObservedAt: "Última observación",
      lane: "Lane",
      positiveRate: "Tasa positiva",
      pendingCount: "Pendientes",
      settledCount: "Liquidados",
      averageHypotheticalPnlPct: "PnL hipotético",
      averageMfePct: "MFE",
      averageMaePct: "MAE",
      reasonBreakdown: "Desglose",
      profitFactorByReason: "Profit factor",
      rrThresholdSimulation: "Simulación RR",
      lastSettledAt: "Última liquidación",
      candidateReadyCycleRate: "Cycle ready",
      eligibleCycleRate: "Cycle eligible",
      opportunityStarvation: "Starvation",
      dominantRejectionReason: "Razón dominante",
      rejectionCombinations: "Combinaciones",
      regimeDistribution: "Distribución",
      windowCycles: "Ciclos",
      windowHours: "Horas",
      totalCandidates: "Candidatos",
      totalEligible: "Elegibles",
      expectedCandidateReadyPerDay: "Ready/día",
      expectedEligibleCyclesPerDay: "Elegibles/día",
      filterSurvival: "Filtro",
      threshold: "Threshold",
      includedCount: "Incluidos",
      positiveCount: "Positivos",
      grossWinsPct: "Ganancias",
      grossLossesPct: "Pérdidas",
      profitFactor: "PF",
      maxDrawdownPct: "Max DD",
      variance: "Varianza",
      share: "Share",
    },
  },
  en: {
    title: "Beta Live Depth",
    description:
      "Internal layers that deepen the observatory with existing real Futures Lab data.",
    sections: {
      scanner: {
        title: "Scanner Detail",
        description: "Scan detail and market ranking context.",
      },
      decisions: {
        title: "Decision Context",
        description: "Expanded context from recent lab decisions.",
      },
      setups: {
        title: "Setup Depth",
        description: "Historical setup memory with deeper performance metrics.",
      },
      ghosts: {
        title: "Ghost Outcomes",
        description: "Post-evaluation reading of rejected opportunities.",
      },
      diagnostics: {
        title: "Diagnostic Context",
        description: "Operational context around candidate survival and rejection reasons.",
      },
    },
    empty: "No beta live data is available.",
    fields: {
      scanBatchId: "Batch",
      lastPrice: "Last price",
      quoteVolume: "Quote volume",
      rangePct: "Range",
      longShortBalance: "Long/short balance",
      orderValid: "Order valid",
      rankingReason: "Ranking reason",
      priceChangePct: "Change %",
      trendStrengthPct: "Trend strength",
      realizedVolatilityPct: "Realized volatility",
      fundingRate: "Funding",
      decisionType: "Type",
      environment: "Environment",
      directionHint: "Bias",
      selectedSide: "Side",
      signalOk: "Signal OK",
      estimatedRrRatio: "Estimated R/R",
      trendAlignmentLabel: "Alignment",
      trendSupportsDirection: "Trend supports",
      setupKey: "Setup",
      setupKeyVersion: "Version",
      oracleRecommendation: "Oracle",
      capitalProfile: "Capital profile",
      operatingCapital: "Operating capital",
      autoEntryEnabled: "Auto entry",
      autoExitEnabled: "Auto exit",
      takeProfitPct: "TP %",
      stopLossPct: "SL %",
      takeProfitUsdt: "TP USDT",
      stopLossUsdt: "SL USDT",
      leverage: "Leverage",
      tradeCount: "Trades",
      winCount: "Wins",
      winRate: "Win rate",
      pnlTotal: "Total PnL",
      averagePnl: "Avg PnL",
      averagePnlPct: "Avg PnL %",
      averageCapitalReference: "Capital ref.",
      averageHoldTicks: "Hold ticks",
      averageWinPnl: "Win PnL",
      averageLossAbs: "Loss abs.",
      lastRealizedPnl: "Last PnL",
      lastRealizedPnlPct: "Last PnL %",
      cooldownMultiplier: "Cooldown",
      suggestedTakeProfitUsdt: "Suggested TP",
      suggestedStopLossUsdt: "Suggested SL",
      lastCloseReason: "Last close",
      healthScore: "Health",
      summaryText: "Summary",
      lastObservedAt: "Last observed",
      lane: "Lane",
      positiveRate: "Positive rate",
      pendingCount: "Pending",
      settledCount: "Settled",
      averageHypotheticalPnlPct: "Hypothetical PnL",
      averageMfePct: "MFE",
      averageMaePct: "MAE",
      reasonBreakdown: "Breakdown",
      profitFactorByReason: "Profit factor",
      rrThresholdSimulation: "RR simulation",
      lastSettledAt: "Last settled",
      candidateReadyCycleRate: "Candidate-ready cycle rate",
      eligibleCycleRate: "Eligible cycle rate",
      opportunityStarvation: "Starvation",
      dominantRejectionReason: "Dominant reason",
      rejectionCombinations: "Combinations",
      regimeDistribution: "Distribution",
      windowCycles: "Cycles",
      windowHours: "Hours",
      totalCandidates: "Candidates",
      totalEligible: "Eligible",
      expectedCandidateReadyPerDay: "Ready/day",
      expectedEligibleCyclesPerDay: "Eligible/day",
      filterSurvival: "Filter",
      threshold: "Threshold",
      includedCount: "Included",
      positiveCount: "Positive",
      grossWinsPct: "Wins",
      grossLossesPct: "Losses",
      profitFactor: "PF",
      maxDrawdownPct: "Max DD",
      variance: "Variance",
      share: "Share",
    },
  },
} as const;

export function getBetaLiveCopy(locale: Locale) {
  return copy[locale];
}
