import type { Locale } from "@/lib/i18n";

const copy = {
  es: {
    title: "Profundidad Beta Live",
    description:
      "Capas internas que amplían el observatory con datos reales ya existentes de Futures Lab.",
    sections: {
      scanner: {
        title: "Scanner Detail",
        description: "¿Por qué este mercado está rankeado?",
      },
      decisions: {
        title: "Decision Context",
        description: "¿Qué decidió Futures Lab?",
      },
      setups: {
        title: "Setup Depth",
        description: "¿Qué historial tiene este Setup?",
      },
      ghosts: {
        title: "Ghost Outcomes",
        description: "¿Qué ocurrió con oportunidades descartadas?",
      },
      diagnostics: {
        title: "Diagnostic Context",
        description: "¿Qué está frenando oportunidades?",
      },
    },
    empty: "No hay datos beta live disponibles.",
    fields: {
      scanBatchId: "Batch",
      lastPrice: "Último precio",
      quoteVolume: "Liquidity volume",
      rangePct: "Range observed",
      longShortBalance: "Long/short balance",
      orderValid: "Order ready",
      rankingReason: "Ranking reason",
      priceChangePct: "Price change",
      trendStrengthPct: "Trend strength",
      realizedVolatilityPct: "Realized volatility",
      fundingRate: "Funding rate",
      decisionType: "Decision type",
      environment: "Environment",
      directionHint: "Directional bias",
      selectedSide: "Side",
      signalOk: "Signal",
      estimatedRrRatio: "RR estimate",
      trendAlignmentLabel: "Trend alignment",
      trendSupportsDirection: "Trend supports direction",
      setupKey: "Setup",
      setupKeyVersion: "Versión",
      oracleRecommendation: "Oracle guidance",
      capitalProfile: "Capital profile",
      operatingCapital: "Operating capital",
      autoEntryEnabled: "Auto entry",
      autoExitEnabled: "Auto exit",
      takeProfitPct: "TP %",
      stopLossPct: "SL %",
      takeProfitUsdt: "TP USDT",
      stopLossUsdt: "SL USDT",
      leverage: "Leverage",
      tradeCount: "Trades",
      winCount: "Wins",
      winRate: "Win rate",
      pnlTotal: "PnL total",
      averagePnl: "Avg PnL",
      averagePnlPct: "Avg PnL %",
      averageCapitalReference: "Capital ref.",
      averageHoldTicks: "Hold ticks",
      averageWinPnl: "Win PnL",
      averageLossAbs: "Loss abs.",
      lastRealizedPnl: "Last PnL",
      lastRealizedPnlPct: "Last PnL %",
      cooldownMultiplier: "Cooldown",
      suggestedTakeProfitUsdt: "Suggested TP",
      suggestedStopLossUsdt: "Suggested SL",
      lastCloseReason: "Last close",
      healthScore: "Health score",
      summaryText: "Summary",
      lastObservedAt: "Last observed",
      lane: "Lane",
      positiveRate: "Positive rate",
      pendingCount: "Pending",
      settledCount: "Settled",
      averageHypotheticalPnlPct: "Hypothetical PnL",
      averageMfePct: "MFE",
      averageMaePct: "MAE",
      reasonBreakdown: "Occurrences",
      profitFactorByReason: "Profit factor",
      rrThresholdSimulation: "RR simulation",
      lastSettledAt: "Last settled",
      candidateReadyCycleRate: "Candidate-ready cycle rate",
      eligibleCycleRate: "Eligible cycle rate",
      opportunityStarvation: "Hours without eligible Setup",
      dominantRejectionReason: "Dominant rejection reason",
      rejectionCombinations: "Rejection combinations",
      regimeDistribution: "Distribution",
      windowCycles: "Cycles",
      windowHours: "Hours",
      totalCandidates: "Candidates",
      totalEligible: "Eligible",
      expectedCandidateReadyPerDay: "Ready/day",
      expectedEligibleCyclesPerDay: "Eligible/day",
      filterSurvival: "Filter survival",
      threshold: "Threshold",
      includedCount: "Incluidos",
      positiveCount: "Positivos",
      grossWinsPct: "Ganancias",
      grossLossesPct: "Pérdidas",
      profitFactor: "PF",
      maxDrawdownPct: "Max DD",
      variance: "Varianza",
      share: "Share",
    },
    tooltips: {
      quoteVolume: "Más volumen suele indicar más liquidez disponible para el scanner.",
      rangePct: "Rango observado en la ventana analizada.",
      longShortBalance: "Equilibrio entre presión long y short dentro del scanner.",
      orderValid: "Indica si el mercado cumple las condiciones operables del scanner.",
      priceChangePct: "Variación de precio observada en la ventana del scanner.",
      trendStrengthPct: "Intensidad de la tendencia detectada por Futures Lab.",
      realizedVolatilityPct: "Volatilidad observada durante la ventana analizada.",
      fundingRate: "Costo o sesgo de funding del mercado de futures.",
      signalOk: "Indica si la decisión superó la validación interna.",
      estimatedRrRatio: "Relación entre la ganancia esperada y la pérdida estimada.",
      trendAlignmentLabel: "Resume qué tan alineada está la decisión con la tendencia.",
      trendSupportsDirection: "Indica si la tendencia apoya el lado elegido.",
      pnlTotal: "Resultado acumulado histórico del Setup.",
      averagePnlPct: "PnL promedio expresado como porcentaje.",
      healthScore: "Señal agregada de salud histórica del Setup.",
      lastCloseReason: "Motivo más reciente de cierre observado para este Setup.",
      positiveRate: "Proporción de resultados favorables en oportunidades rechazadas.",
      averageHypotheticalPnlPct: "PnL hipotético promedio si se hubiera tomado la oportunidad.",
      profitFactor: "Ganancia bruta dividida por pérdida bruta.",
      opportunityStarvation: "Tiempo transcurrido desde el último Setup elegible.",
      dominantRejectionReason: "Razón que más se repite al descartar oportunidades.",
    },
  },
  en: {
    title: "Beta Live Depth",
    description:
      "Internal layers that deepen the observatory with existing real Futures Lab data.",
    sections: {
      scanner: {
        title: "Scanner Detail",
        description: "Why is this market ranked?",
      },
      decisions: {
        title: "Decision Context",
        description: "What did Futures Lab decide?",
      },
      setups: {
        title: "Setup Depth",
        description: "What history does this Setup have?",
      },
      ghosts: {
        title: "Ghost Outcomes",
        description: "What happened with rejected opportunities?",
      },
      diagnostics: {
        title: "Diagnostic Context",
        description: "What is blocking opportunities?",
      },
    },
    empty: "No beta live data is available.",
    fields: {
      scanBatchId: "Batch",
      lastPrice: "Last price",
      quoteVolume: "Liquidity volume",
      rangePct: "Range observed",
      longShortBalance: "Long/short balance",
      orderValid: "Order ready",
      rankingReason: "Ranking reason",
      priceChangePct: "Price change",
      trendStrengthPct: "Trend strength",
      realizedVolatilityPct: "Realized volatility",
      fundingRate: "Funding rate",
      decisionType: "Decision type",
      environment: "Environment",
      directionHint: "Directional bias",
      selectedSide: "Side",
      signalOk: "Signal",
      estimatedRrRatio: "RR estimate",
      trendAlignmentLabel: "Trend alignment",
      trendSupportsDirection: "Trend supports direction",
      setupKey: "Setup",
      setupKeyVersion: "Version",
      oracleRecommendation: "Oracle guidance",
      capitalProfile: "Capital profile",
      operatingCapital: "Operating capital",
      autoEntryEnabled: "Auto entry",
      autoExitEnabled: "Auto exit",
      takeProfitPct: "TP %",
      stopLossPct: "SL %",
      takeProfitUsdt: "TP USDT",
      stopLossUsdt: "SL USDT",
      leverage: "Leverage",
      tradeCount: "Trades",
      winCount: "Wins",
      winRate: "Win rate",
      pnlTotal: "Total PnL",
      averagePnl: "Avg PnL",
      averagePnlPct: "Avg PnL %",
      averageCapitalReference: "Capital ref.",
      averageHoldTicks: "Hold ticks",
      averageWinPnl: "Win PnL",
      averageLossAbs: "Loss abs.",
      lastRealizedPnl: "Last PnL",
      lastRealizedPnlPct: "Last PnL %",
      cooldownMultiplier: "Cooldown",
      suggestedTakeProfitUsdt: "Suggested TP",
      suggestedStopLossUsdt: "Suggested SL",
      lastCloseReason: "Last close",
      healthScore: "Health score",
      summaryText: "Summary",
      lastObservedAt: "Last observed",
      lane: "Lane",
      positiveRate: "Positive rate",
      pendingCount: "Pending",
      settledCount: "Settled",
      averageHypotheticalPnlPct: "Hypothetical PnL",
      averageMfePct: "MFE",
      averageMaePct: "MAE",
      reasonBreakdown: "Occurrences",
      profitFactorByReason: "Profit factor",
      rrThresholdSimulation: "RR simulation",
      lastSettledAt: "Last settled",
      candidateReadyCycleRate: "Candidate-ready cycle rate",
      eligibleCycleRate: "Eligible cycle rate",
      opportunityStarvation: "Hours without eligible Setup",
      dominantRejectionReason: "Dominant rejection reason",
      rejectionCombinations: "Rejection combinations",
      regimeDistribution: "Distribution",
      windowCycles: "Cycles",
      windowHours: "Hours",
      totalCandidates: "Candidates",
      totalEligible: "Eligible",
      expectedCandidateReadyPerDay: "Ready/day",
      expectedEligibleCyclesPerDay: "Eligible/day",
      filterSurvival: "Filter",
      threshold: "Threshold",
      includedCount: "Included",
      positiveCount: "Positive",
      grossWinsPct: "Wins",
      grossLossesPct: "Losses",
      profitFactor: "PF",
      maxDrawdownPct: "Max DD",
      variance: "Variance",
      share: "Share",
    },
    tooltips: {
      quoteVolume: "Higher volume usually means more liquidity for the scanner.",
      rangePct: "Observed range across the scanned window.",
      longShortBalance: "Balance between long and short pressure inside the scanner.",
      orderValid: "Indicates whether the market passes the scanner's operability checks.",
      priceChangePct: "Price movement observed during the scan window.",
      trendStrengthPct: "Strength of the trend detected by Futures Lab.",
      realizedVolatilityPct: "Observed volatility during the evaluated window.",
      fundingRate: "Funding cost or bias in the futures market.",
      signalOk: "Indicates whether the decision passed internal validation.",
      estimatedRrRatio: "Estimated ratio between expected gain and estimated loss.",
      trendAlignmentLabel: "Summarizes how aligned the decision is with trend context.",
      trendSupportsDirection: "Indicates whether trend supports the chosen side.",
      pnlTotal: "Historical cumulative result for the Setup.",
      averagePnlPct: "Average PnL expressed as a percentage.",
      healthScore: "Aggregated historical health signal for the Setup.",
      lastCloseReason: "Most recent observed reason a Setup was closed.",
      positiveRate: "Share of favorable outcomes among rejected opportunities.",
      averageHypotheticalPnlPct: "Average hypothetical PnL if the opportunity had been taken.",
      profitFactor: "Gross profit divided by gross loss.",
      opportunityStarvation: "Time since the last eligible Setup appeared.",
      dominantRejectionReason: "Most repeated reason for rejecting opportunities.",
    },
  },
} as const;

export function getBetaLiveCopy(locale: Locale) {
  return copy[locale];
}
