import {
  mockOpportunityRankings,
  mockPatternDiscovery,
  mockRegimeAnalysis,
} from "@/services/api/mock-data";
import { createIntelligenceBrief } from "@/services/api/intelligence-brief";
import type {
  ChangeAwareness,
  GhostTracking,
  IntelligenceSnapshot,
  LabDecision,
  MarketRanking,
  MarketSummary,
  SetupMemory,
} from "@/types/intelligence";

const DEMO_TIMESTAMP = "2026-06-08T12:00:00.000Z";

export function createPublicDemoSnapshot(): IntelligenceSnapshot {
  const marketRankings = createMarketRankings();
  const marketSummary = createMarketSummary(marketRankings);
  const labDecisions = createLabDecisions();
  const setupMemory = createSetupMemory();
  const ghostTracking = createGhostTracking();
  const changeAwareness = createChangeAwareness();

  return {
    generatedAt: DEMO_TIMESTAMP,
    changeAwareness,
    intelligenceBrief: createIntelligenceBrief({
      ghostTracking,
      labDecisions,
      marketRankings,
      marketSummary,
      setupMemory,
    }),
    labDecisions,
    marketSummary,
    marketRankings,
    setupMemory,
    ghostTracking,
    betaLiveInsights: null,
    opportunityRankings: mockOpportunityRankings,
    patternDiscovery: mockPatternDiscovery,
    regimeAnalysis: mockRegimeAnalysis,
  };
}

function createMarketRankings(): MarketRanking[] {
  return [
    {
      rank: 1,
      symbol: "BTCUSDT",
      market: "Binance USDT Perpetual",
      consistencyScore: 94,
      regime: "Momentum Expansion",
      direction: "Bullish",
      rankingReason: "Broad participation, clean trend structure and strong follow-through.",
      priceChangePct: 2.8,
      realizedVolatilityPct: 1.9,
      trendStrengthPct: 7.2,
      fundingRate: 0.006,
      scannedAt: DEMO_TIMESTAMP,
      scanBatchId: "demo-batch-1",
      lastPrice: 68250,
      quoteVolume: 1523400000,
      rangePct: 4.1,
      longShortBalance: 0.62,
      orderValid: true,
    },
    {
      rank: 2,
      symbol: "ETHUSDT",
      market: "Binance USDT Perpetual",
      consistencyScore: 89,
      regime: "Trend Stabilization",
      direction: "Bullish",
      rankingReason: "Directional pressure remains elevated with improving consistency.",
      priceChangePct: 1.7,
      realizedVolatilityPct: 1.4,
      trendStrengthPct: 6.4,
      fundingRate: 0.003,
      scannedAt: DEMO_TIMESTAMP,
      scanBatchId: "demo-batch-1",
      lastPrice: 3520,
      quoteVolume: 892400000,
      rangePct: 3.2,
      longShortBalance: 0.58,
      orderValid: true,
    },
    {
      rank: 3,
      symbol: "SOLUSDT",
      market: "Binance USDT Perpetual",
      consistencyScore: 82,
      regime: "Compression Release",
      direction: "Neutral",
      rankingReason: "Range compression is resolving after several quiet sessions.",
      priceChangePct: 1.1,
      realizedVolatilityPct: 2.3,
      trendStrengthPct: 4.9,
      fundingRate: -0.001,
      scannedAt: DEMO_TIMESTAMP,
      scanBatchId: "demo-batch-1",
      lastPrice: 158.4,
      quoteVolume: 543900000,
      rangePct: 5.3,
      longShortBalance: 0.51,
      orderValid: false,
    },
  ];
}

function createMarketSummary(rankings: MarketRanking[]): MarketSummary {
  return {
    totalMarkets: rankings.length,
    topSymbol: rankings[0]?.symbol ?? "None",
    topScore: rankings[0]?.consistencyScore ?? 0,
    lastUpdatedAt: DEMO_TIMESTAMP,
    freshness: [
      {
        label: "Scanner",
        timestamp: DEMO_TIMESTAMP,
        ageMinutes: 4,
        isFresh: true,
      },
      {
        label: "Decisions",
        timestamp: DEMO_TIMESTAMP,
        ageMinutes: 18,
        isFresh: true,
      },
      {
        label: "Observations",
        timestamp: DEMO_TIMESTAMP,
        ageMinutes: 22,
        isFresh: true,
      },
    ],
  };
}

function createLabDecisions(): LabDecision[] {
  return [
    {
      symbol: "BTCUSDT",
      selectedSide: "Long",
      decisionType: "Candidate Ready",
      reason: "Trend structure and liquidity supported a clean research setup.",
      signalStatus: "Signal OK",
      rewardRisk: 2.4,
      setupKey: "trend-continuation-long",
      observedAt: DEMO_TIMESTAMP,
      scanBatchId: "demo-batch-1",
      setupKeyVersion: "v1",
      environment: "demo",
      directionHint: "Bullish",
      capitalProfile: "moderate",
      operatingCapital: 2500,
      autoEntryEnabled: false,
      autoExitEnabled: true,
      takeProfitPct: 1.2,
      stopLossPct: 0.6,
      takeProfitUsdt: 30,
      stopLossUsdt: 15,
      leverage: 3,
      oracleRecommendation: "Proceed",
      trendAlignmentLabel: "Aligned",
      trendSupportsDirection: true,
    },
    {
      symbol: "ETHUSDT",
      selectedSide: "Long",
      decisionType: "Context Watch",
      reason: "Price action remained constructive but still needed confirmation.",
      signalStatus: "Unknown",
      rewardRisk: 1.8,
      setupKey: "momentum-follow-through",
      observedAt: DEMO_TIMESTAMP,
      scanBatchId: "demo-batch-1",
      setupKeyVersion: "v1",
      environment: "demo",
      directionHint: "Bullish",
      capitalProfile: "moderate",
      operatingCapital: 1800,
      autoEntryEnabled: false,
      autoExitEnabled: true,
      takeProfitPct: 1,
      stopLossPct: 0.55,
      takeProfitUsdt: 18,
      stopLossUsdt: 9.9,
      leverage: 2,
      oracleRecommendation: "Watch",
      trendAlignmentLabel: "Partially aligned",
      trendSupportsDirection: true,
    },
    {
      symbol: "SOLUSDT",
      selectedSide: "Neutral",
      decisionType: "Rejected",
      reason: "Compression was present, but directional evidence was incomplete.",
      signalStatus: "Signal not OK",
      rewardRisk: 1.2,
      setupKey: "compression-release",
      observedAt: DEMO_TIMESTAMP,
      scanBatchId: "demo-batch-1",
      setupKeyVersion: "v1",
      environment: "demo",
      directionHint: "Neutral",
      capitalProfile: "moderate",
      operatingCapital: 1200,
      autoEntryEnabled: false,
      autoExitEnabled: true,
      takeProfitPct: 0.8,
      stopLossPct: 0.4,
      takeProfitUsdt: 9.6,
      stopLossUsdt: 4.8,
      leverage: 1,
      oracleRecommendation: "Reject",
      trendAlignmentLabel: "Misaligned",
      trendSupportsDirection: false,
    },
  ];
}

function createSetupMemory(): SetupMemory[] {
  return [
    {
      setupKey: "trend-continuation-long",
      symbol: "BTCUSDT",
      side: "Long",
      environment: "demo",
      capitalProfile: "moderate",
      lane: "research",
      tradeCount: 128,
      winCount: 86,
      winRate: 0.67,
      healthScore: 84,
      healthLabel: "Healthy",
      pnlTotal: 18.74,
      averagePnl: 0.146,
      averagePnlPct: 0.0146,
      averageCapitalReference: 2500,
      averageHoldTicks: 14,
      averageWinPnl: 0.38,
      averageLossAbs: 0.21,
      lastRealizedPnl: 0.42,
      lastRealizedPnlPct: 0.0168,
      cooldownMultiplier: 1.1,
      suggestedTakeProfitUsdt: 32,
      suggestedStopLossUsdt: 14,
      lastCloseReason: "Trend continuation take profit",
      summaryText:
        "Long trend continuation has remained the strongest historical structure.",
      lastSeenAt: DEMO_TIMESTAMP,
      lastSymbol: "BTCUSDT",
      lastSide: "Long",
      lastObservedAt: DEMO_TIMESTAMP,
    },
    {
      setupKey: "momentum-follow-through",
      symbol: "ETHUSDT",
      side: "Long",
      environment: "demo",
      capitalProfile: "moderate",
      lane: "research",
      tradeCount: 94,
      winCount: 57,
      winRate: 0.61,
      healthScore: 76,
      healthLabel: "Stable",
      pnlTotal: 11.2,
      averagePnl: 0.119,
      averagePnlPct: 0.0119,
      averageCapitalReference: 1800,
      averageHoldTicks: 10,
      averageWinPnl: 0.31,
      averageLossAbs: 0.18,
      lastRealizedPnl: 0.28,
      lastRealizedPnlPct: 0.0156,
      cooldownMultiplier: 1.05,
      suggestedTakeProfitUsdt: 20,
      suggestedStopLossUsdt: 10,
      lastCloseReason: "Follow-through retest",
      summaryText:
        "Momentum follow-through stays active across several recent observations.",
      lastSeenAt: DEMO_TIMESTAMP,
      lastSymbol: "ETHUSDT",
      lastSide: "Long",
      lastObservedAt: DEMO_TIMESTAMP,
    },
    {
      setupKey: "compression-release",
      symbol: "SOLUSDT",
      side: "Neutral",
      environment: "demo",
      capitalProfile: "moderate",
      lane: "research",
      tradeCount: 52,
      winCount: 29,
      winRate: 0.55,
      healthScore: 61,
      healthLabel: "Watch",
      pnlTotal: 4.91,
      averagePnl: 0.094,
      averagePnlPct: 0.0094,
      averageCapitalReference: 1200,
      averageHoldTicks: 8,
      averageWinPnl: 0.24,
      averageLossAbs: 0.17,
      lastRealizedPnl: 0.11,
      lastRealizedPnlPct: 0.0092,
      cooldownMultiplier: 0.95,
      suggestedTakeProfitUsdt: 12,
      suggestedStopLossUsdt: 6,
      lastCloseReason: "Compression unresolved",
      summaryText:
        "Compression release appears less consistent but still worth tracking.",
      lastSeenAt: DEMO_TIMESTAMP,
      lastSymbol: "SOLUSDT",
      lastSide: "Neutral",
      lastObservedAt: DEMO_TIMESTAMP,
    },
  ];
}

function createGhostTracking(): GhostTracking {
  return {
    pendingCount: 2,
    settledCount: 84,
    positiveRate: 0.62,
    averageHypotheticalPnlPct: 0.38,
    averageMfePct: 1.42,
    averageMaePct: 0.77,
    lastSettledAt: DEMO_TIMESTAMP,
    rrThresholdSimulation: [
      {
        threshold: 1,
        includedCount: 84,
        positiveCount: 52,
        positiveRate: 0.619,
        avgHypotheticalPnlPct: 0.38,
        grossWinsPct: 29.5,
        grossLossesPct: 16.8,
        profitFactor: 1.75,
        maxDrawdownPct: 1.8,
        variance: 0.42,
        avgMaePct: 0.77,
      },
    ],
    records: [
      {
        rejectionReason: "crowded_longs",
        rejectionReasonLabel: "Crowded longs",
        totalCount: 31,
        settledCount: 29,
        settledPositiveCount: 18,
        averageHypotheticalPnlPct: 0.44,
        profitFactor: 1.41,
      },
      {
        rejectionReason: "weak_trend",
        rejectionReasonLabel: "Weak trend",
        totalCount: 27,
        settledCount: 26,
        settledPositiveCount: 15,
        averageHypotheticalPnlPct: 0.31,
        profitFactor: 1.18,
      },
      {
        rejectionReason: "high_volatility",
        rejectionReasonLabel: "High volatility",
        totalCount: 26,
        settledCount: 29,
        settledPositiveCount: 19,
        averageHypotheticalPnlPct: 0.39,
        profitFactor: 1.07,
      },
    ],
  };
}

function createChangeAwareness(): ChangeAwareness {
  return {
    currentWindow: "Last 24 hours",
    baselineWindow: "Previous 24 hours",
    items: [
      {
        label: "Ranking leader",
        statement: "BTCUSDT remains the highest-ranked market.",
        detail: "Leader score held near the top of the current observation set.",
      },
      {
        label: "Directional bias",
        statement: "Long-bias opportunities represented the larger share of scanner activity.",
        detail: "The current window shows more bullish than bearish observations.",
      },
      {
        label: "Research activity",
        statement: "Candidate Ready decisions were the most common recent research action.",
        detail: "Context Watch activity remained present but secondary.",
      },
      {
        label: "Ghost tracking",
        statement: "Ghost tracking positive rate improved relative to the previous window.",
        detail: "Rejected crowded-long candidates continued to show useful post-evaluation feedback.",
      },
    ],
  };
}
