import { ArrowRight, BarChart3, LineChart, Radar } from "lucide-react";
import { ButtonLink } from "@/components/ui/button";

const pillars = [
  {
    title: "Market rankings",
    description: "Rank futures markets by consistency, regime and directional context.",
    icon: BarChart3,
  },
  {
    title: "Pattern discovery",
    description: "Surface recurring statistical patterns generated by Futures Lab.",
    icon: Radar,
  },
  {
    title: "Regime analysis",
    description: "Summarize market state without trade execution or financial advice.",
    icon: LineChart,
  },
];

export function LandingPage() {
  return (
    <main className="min-h-screen bg-background text-foreground">
      <section className="border-b">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5">
          <p className="text-sm font-semibold">POC Intelligence</p>
          <ButtonLink href="/dashboard" size="sm">
            Open dashboard
            <ArrowRight className="h-4 w-4" aria-hidden="true" />
          </ButtonLink>
        </div>
      </section>
      <section className="mx-auto grid max-w-6xl gap-10 px-6 py-20 lg:grid-cols-[1.1fr_0.9fr] lg:items-center">
        <div>
          <p className="text-sm font-medium text-primary">
            Quantitative market intelligence
          </p>
          <h1 className="mt-4 max-w-3xl text-5xl font-semibold leading-tight tracking-normal">
            ProofOfConsistency Intelligence Platform
          </h1>
          <p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">
            A lightweight SaaS interface for market rankings, opportunity rankings,
            pattern discovery and regime analysis generated by the existing Futures
            Lab backend.
          </p>
          <div className="mt-8 flex flex-wrap gap-3">
            <ButtonLink href="/dashboard" size="lg">
              View intelligence
              <ArrowRight className="h-4 w-4" aria-hidden="true" />
            </ButtonLink>
            <ButtonLink href="/dashboard#markets" variant="outline" size="lg">
              Review rankings
            </ButtonLink>
          </div>
          <p className="mt-6 max-w-xl text-sm text-muted-foreground">
            This platform does not execute trades and does not provide financial advice.
          </p>
        </div>
        <div className="rounded-lg border bg-card p-5">
          <div className="grid grid-cols-2 gap-3">
            <Metric label="Consistency score" value="91" />
            <Metric label="Active regimes" value="3" />
            <Metric label="Patterns found" value="126" />
            <Metric label="Markets ranked" value="4" />
          </div>
          <div className="mt-5 rounded-md border bg-muted p-4">
            <p className="text-sm font-medium">Current top signal</p>
            <p className="mt-2 text-2xl font-semibold">ES Momentum Expansion</p>
            <p className="mt-2 text-sm leading-6 text-muted-foreground">
              Mock snapshot for Phase 1 foundation and Vercel deployment readiness.
            </p>
          </div>
        </div>
      </section>
      <section className="mx-auto grid max-w-6xl gap-4 px-6 pb-16 md:grid-cols-3">
        {pillars.map((pillar) => (
          <article key={pillar.title} className="rounded-lg border bg-card p-5">
            <pillar.icon className="h-5 w-5 text-secondary" aria-hidden="true" />
            <h2 className="mt-4 text-base font-semibold">{pillar.title}</h2>
            <p className="mt-2 text-sm leading-6 text-muted-foreground">
              {pillar.description}
            </p>
          </article>
        ))}
      </section>
    </main>
  );
}

function Metric({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-md border bg-background p-4">
      <p className="text-xs text-muted-foreground">{label}</p>
      <p className="mt-2 text-3xl font-semibold">{value}</p>
    </div>
  );
}
