import { ArrowRight, BarChart3, LineChart, Radar } from "lucide-react";
import { LanguageSwitcher } from "@/components/layout/language-switcher";
import { PublicDemoBanner } from "@/components/layout/public-demo-banner";
import { ButtonLink } from "@/components/ui/button";
import { getCopy, type Locale } from "@/lib/i18n";

const pillars = [
  {
    key: "markets",
    title: "Market rankings",
    description: "Rank futures markets by consistency, regime and directional context.",
    icon: BarChart3,
  },
  {
    key: "patterns",
    title: "Pattern discovery",
    description: "Surface recurring statistical patterns generated by Futures Lab.",
    icon: Radar,
  },
  {
    key: "regimes",
    title: "Regime analysis",
    description: "Summarize market state without trade execution or financial advice.",
    icon: LineChart,
  },
] as const;

type LandingPageProps = {
  locale: Locale;
};

export function LandingPage({ locale }: LandingPageProps) {
  const copy = getCopy(locale);

  return (
    <main className="min-h-screen bg-background text-foreground">
      <PublicDemoBanner locale={locale} />
      <section className="border-b">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5">
          <p className="text-sm font-semibold">POC Intelligence</p>
          <div className="flex items-center gap-3">
            <div className="rounded-full border bg-muted px-3 py-1 text-xs font-medium text-muted-foreground">
              {copy.banner.title}
            </div>
            <LanguageSwitcher locale={locale} />
            <ButtonLink href="/dashboard" size="sm">
              {copy.topBar.overview}
              <ArrowRight className="h-4 w-4" aria-hidden="true" />
            </ButtonLink>
          </div>
        </div>
      </section>
      <section className="mx-auto grid max-w-6xl gap-10 px-6 py-20 lg:grid-cols-[1.1fr_0.9fr] lg:items-center">
        <div>
          <p className="text-sm font-medium text-primary">{copy.landing.eyebrow}</p>
          <h1 className="mt-4 max-w-3xl text-5xl font-semibold leading-tight tracking-normal">
            {copy.landing.title}
          </h1>
          <p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">
            {copy.landing.description}
          </p>
          <div className="mt-8 flex flex-wrap gap-3">
            <ButtonLink href="/dashboard" size="lg">
              {copy.landing.primaryAction}
              <ArrowRight className="h-4 w-4" aria-hidden="true" />
            </ButtonLink>
            <ButtonLink href="/dashboard#markets" variant="outline" size="lg">
              {copy.landing.secondaryAction}
            </ButtonLink>
          </div>
          <p className="mt-6 max-w-xl text-sm text-muted-foreground">
            {copy.landing.disclaimer}
          </p>
        </div>
        <div className="rounded-lg border bg-card p-5">
          <div className="grid grid-cols-2 gap-3">
            <Metric label={copy.landing.metrics.consistency} value="91" />
            <Metric label={copy.landing.metrics.regimes} value="3" />
            <Metric label={copy.landing.metrics.patterns} value="126" />
            <Metric label={copy.landing.metrics.markets} value="4" />
          </div>
          <div className="mt-5 rounded-md border bg-muted p-4">
            <p className="text-sm font-medium">{copy.landing.metrics.topSignal}</p>
            <p className="mt-2 text-2xl font-semibold">ES Momentum Expansion</p>
            <p className="mt-2 text-sm leading-6 text-muted-foreground">
              {copy.landing.metrics.topSignalDetail}
            </p>
          </div>
        </div>
      </section>
      <section className="mx-auto grid max-w-6xl gap-4 px-6 pb-16 md:grid-cols-3">
        {pillars.map((pillar) => (
          <article key={pillar.key} className="rounded-lg border bg-card p-5">
            <pillar.icon className="h-5 w-5 text-secondary" aria-hidden="true" />
            <h2 className="mt-4 text-base font-semibold">{copy.landing.pillars[pillar.key].title}</h2>
            <p className="mt-2 text-sm leading-6 text-muted-foreground">
              {copy.landing.pillars[pillar.key].description}
            </p>
          </article>
        ))}
      </section>
    </main>
  );
}

function Metric({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-md border bg-background p-4">
      <p className="text-xs text-muted-foreground">{label}</p>
      <p className="mt-2 text-3xl font-semibold">{value}</p>
    </div>
  );
}
